[helper]
path = "/usr/local/Cellar/rust/1.19.0"     # Reserved for future helper path and configurations
[options]
save_buffers_before_run = true             # Saving buffers before every cargo command run
general_warnings = true                    # Show general warnings
[project]
auto_format_timing = 5                     # Run auto formatting for project for specified interval (seconds)%